# Generated by Django 5.2.7 on 2025-11-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='categorie',
            field=models.CharField(choices=[('strategie', 'Stratégie'), ('ia', 'IA & Communication'), ('institutionnel', 'Institutionnel'), ('evenement', 'Événementiel'), ('autre', 'Autre')], default='autre', max_length=50, verbose_name='Catégorie'),
        ),
    ]
