# Generated by Django 5.2.7 on 2025-11-14 11:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partenaires/')),
                ('site_web', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('date_ajout', models.DateTimeField(default=django.utils.timezone.now)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
