# Generated by Django 5.2.8 on 2025-11-09 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projets/'),
        ),
    ]
